import AppLayout from "@/components/layout";
import "./global.css";
import Providers from "@/components/providers";

export const metadata = {
	title: "Welcome to web",
	description: "Generated by create-nx-workspace",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<Providers>
					<AppLayout>{children}</AppLayout>
				</Providers>
			</body>
		</html>
	);
}
