name: Feature Request
description: File a feature request.
title: "[Feature]: "
labels: ["feature", "triage"]
projects: ["windbase/1"]
assignees:
  - mxvsh
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: feature-request
    attributes:
      label: Feature Request
      description: What feature would you like to see?
      placeholder: Tell us what you want!
      value: "A feature request!"
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Low
        - Medium
        - High
        - Critical
      default: Medium