import type { ElementType } from './elementTypes';
import type { ElementDefinition } from './types/element-definition';

export const elements: Record<ElementType, ElementDefinition[]> = {
	layout: [
		{
			id: 'div',
			type: 'layout',
			tag: 'div',
			classes: [],
			children: [],
		},
		{
			id: 'container',
			type: 'layout',
			tag: 'div',
			classes: ['container', 'mx-auto', 'px-4'],
			children: [],
		},
		{
			id: 'grid',
			type: 'layout',
			tag: 'div',
			classes: ['grid', 'grid-cols-2', 'gap-4'],
			children: [],
		},
		{
			id: 'flex',
			type: 'layout',
			tag: 'div',
			classes: ['flex', 'items-center', 'justify-between'],
			children: [],
		},
	],
	form: [
		{
			id: 'input',
			type: 'form',
			tag: 'input',
			classes: ['border', 'rounded', 'px-4', 'py-2'],
			children: [],
			inputAttributes: [
				{
					attribute: 'placeholder',
					type: 'text',
					label: 'Placeholder',
				},
				{
					attribute: 'type',
					type: 'select',
					label: 'Type',
					options: ['text', 'number', 'email', 'password'],
				},
			],
		},
		{
			id: 'button',
			type: 'form',
			tag: 'button',
			classes: ['border', 'border-gray-300', 'px-4', 'py-2', 'rounded'],
			content: 'Button',
			isContentEditable: true,
			children: [],
		},
		{
			id: 'label',
			type: 'form',
			tag: 'label',
			classes: ['text-sm', 'font-medium'],
			content: 'Label text',
			isContentEditable: true,
			children: [],
		},
	],
	media: [
		{
			id: 'image',
			type: 'media',
			tag: 'img',
			classes: ['w-full', 'h-auto', 'rounded'],
			children: [],
			inputAttributes: [
				{
					attribute: 'src',
					type: 'text',
					label: 'Source',
				},
			],
		},
	],
	text: [
		{
			id: 'text',
			type: 'other',
			tag: 'p',
			classes: ['text-base'],
			content: 'Text content',
			isContentEditable: true,
			children: [],
		},
		{
			id: 'heading-1',
			type: 'other',
			tag: 'h1',
			classes: ['text-4xl', 'font-bold'],
			content: 'Heading 1',
			isContentEditable: true,
			children: [],
		},
		{
			id: 'heading-2',
			type: 'other',
			tag: 'h2',
			classes: ['text-3xl', 'font-bold'],
			content: 'Heading 2',
			isContentEditable: true,
			children: [],
		},
		{
			id: 'heading-3',
			type: 'other',
			tag: 'h3',
			classes: ['text-2xl', 'font-bold'],
			content: 'Heading 3',
			isContentEditable: true,
			children: [],
		},
		{
			id: 'heading-4',
			type: 'other',
			tag: 'h4',
			classes: ['text-xl', 'font-bold'],
			content: 'Heading 4',
			isContentEditable: true,
			children: [],
		},
		{
			id: 'heading-5',
			type: 'other',
			tag: 'h5',
			classes: ['text-lg', 'font-bold'],
			content: 'Heading 5',
			isContentEditable: true,
			children: [],
		},
		{
			id: 'heading-6',
			type: 'other',
			tag: 'h6',
			classes: ['text-base', 'font-bold'],
			content: 'Heading 6',
			isContentEditable: true,
			children: [],
		},
		{
			id: 'span',
			type: 'other',
			tag: 'span',
			classes: [],
			content: 'Span text',
			isContentEditable: true,
			children: [],
		},
		{
			id: 'italic',
			type: 'other',
			tag: 'i',
			classes: ['italic'],
			content: 'Italic text',
			isContentEditable: true,
			children: [],
		},
		{
			id: 'emphasis',
			type: 'other',
			tag: 'em',
			classes: ['italic'],
			content: 'Emphasized text',
			isContentEditable: true,
			children: [],
		},
		{
			id: 'strong',
			type: 'other',
			tag: 'strong',
			classes: ['font-bold'],
			content: 'Strong text',
			isContentEditable: true,
			children: [],
		},
		{
			id: 'link',
			type: 'other',
			tag: 'a',
			classes: ['text-blue-600', 'hover:text-blue-800', 'underline'],
			content: 'Link text',
			isContentEditable: true,
			children: [],
			inputAttributes: [
				{
					attribute: 'href',
					type: 'text',
					label: 'URL',
				},
				{
					attribute: 'target',
					type: 'select',
					label: 'Target',
					options: ['_self', '_blank', '_parent', '_top'],
				},
			],
		},
	],
	other: [
		{
			id: 'unordered-list',
			type: 'other',
			tag: 'ul',
			classes: ['list-disc', 'list-inside'],
			children: [],
		},
		{
			id: 'ordered-list',
			type: 'other',
			tag: 'ol',
			classes: ['list-decimal', 'list-inside'],
			children: [],
		},
		{
			id: 'list-item',
			type: 'other',
			tag: 'li',
			classes: ['list-inside'],
			children: [],
		},
		{
			id: 'definition-list',
			type: 'other',
			tag: 'dl',
			classes: ['space-y-2'],
			children: [],
		},
		{
			id: 'definition-term',
			type: 'other',
			tag: 'dt',
			classes: ['font-semibold'],
			content: 'Definition term',
			isContentEditable: true,
			children: [],
		},
		{
			id: 'definition-description',
			type: 'other',
			tag: 'dd',
			classes: ['ml-4'],
			content: 'Definition description',
			isContentEditable: true,
			children: [],
		},
	],
};
